server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  application:
    name: TATACHANGE
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/change?serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowMultiQueries=true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: com/tata/change/**/mapper/**Mapper.xml,com/tata/change/initialization/db/**Mapper.xml
  type-aliases-package: com.tata.change.user.demo,com.tata.change.shiro.demo,com.tata.change.util,com.tata.change.base.demo,com.tata.change.menu.demo
lucene:
  directory: lucene/index
project:
  status: de
