server:
  port: 8080
spring:
  application:
    name: TATACHANGE
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/change?serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowMultiQueries=true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/tata/change/**/mapper/**Mapper.xml
  type-aliases-package: com.tata.change.user.demo,com.tata.change.shiro.demo,com.tata.change.util